apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-char-device-plugin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-char-device-plugin
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-char-device-plugin
subjects:
  - kind: ServiceAccount
    name: k8s-char-device-plugin
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: k8s-char-device-plugin
  apiGroup: rbac.authorization.k8s.io